//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secondhand.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public int Year { get; set; }
        public int Price { get; set; }
        public int SellerUserId { get; set; }
        public Nullable<int> BuyerUserId { get; set; }
    
        public virtual User Seller { get; set; }
        public virtual User Buyer { get; set; }
    }
}
